version: '3'
services:
  api:
    image: dlamarg/careertracker/api:latest
    build: ./careertracker
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=career_tracker_db
    ports:
      - '5457:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: